# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test01:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_01(self):
        self.driver.get("https://www.python.org/")
        self.driver.set_window_size(1246, 834)
        self.driver.find_element(By.ID, "id-search-field").click()
        self.driver.find_element(By.ID, "id-search-field").send_keys("pytest")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, "#content > .container").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-recent-events > li:nth-child(1)"
        ).click()
        self.driver.find_element(
            By.CSS_SELECTOR, "li:nth-child(1) .highlighted:nth-child(2)"
        ).click()
        self.driver.find_element(
            By.CSS_SELECTOR, "li:nth-child(1) .highlighted:nth-child(2)"
        ).click()
        element = self.driver.find_element(
            By.CSS_SELECTOR, "li:nth-child(1) .highlighted:nth-child(2)"
        )
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        assert (
            self.driver.find_element(
                By.CSS_SELECTOR, "li:nth-child(1) .highlighted:nth-child(2)"
            ).text
            == "pytest"
        )
